### ISSUE TITLE
R question named list vs. data frame

### ISSUE THREAD

**Issue by thejmazz** [hyginn/Ontoscope#13]
## named list?

Not terribly important, but I'm unsure of what exactly a "named list" is, as a package (GSEABase) creates a class where one of its "slots" is a `list`, but this appears different than a "manually created" named list. So is the first _not_ a named list, or perhaps the number of cols changes how it appears, or perhaps there is something else at play? (I tried coercing `nums` into a character vector). The `fantom` object came from GSEABase with `fantom <- getOBOCollection("ff-phase2-140729.obo")`, which belongs to the [OBOCollection](http://svitsrv25.epfl.ch/R-doc/library/GSEABase/html/OBOCollection-class.html) class.

``` r
> typeof(fantom@.kv)
[1] "list"
> head(fantom@.kv)
     stanza_id            key                value
1    .__Root__ format-version                  1.2
6    .__Root__       ontology ff/subsets/ff-phase2
10 BFO:0000030           name               object
11 BFO:0000030      namespace               FANTOM
12 BFO:0000030           is_a          BFO:0000040
16 BFO:0000040           name      material entity
> head(fantom@.kv$stanza_id)
[1] ".__Root__"   ".__Root__"   "BFO:0000030" "BFO:0000030" "BFO:0000030" "BFO:0000040"
> named_list <- list(nums=c(1,2,3), letters=c("a","b","c"))
> typeof(named_list)
[1] "list"
> head(named_list)
$nums
[1] 1 2 3

$letters
[1] "a" "b" "c"

> head(named_list$nums)
[1] 1 2 3
> named_list <- list(nums=as.character(c(1,2,3)), letters=c("a","b","c"))
> named_list
$nums
[1] "1" "2" "3"

$letters
[1] "a" "b" "c"
> named_list <- list(1:3, nums=as.character(c(1,2,3)), letters=c("a","b","c"))
> named_list
[[1]]
[1] 1 2 3

$nums
[1] "1" "2" "3"

$letters
[1] "a" "b" "c"
```

An alternative way to phrase my question: how to create an object `x` such that `typeof(x)` is `list` and it "appears to look (and act?) like a `data.frame`"...

My confusion with this arose from seeing `x$colName` and I didn't realize objects other than `data.frame`s can use `$`..

Also, let me know if my use of words such as object isn't totally correct. Maybe variable is better.

**Comment by gosuzombie** [comment]
i think you're looking for names(list). it works like colnames(data frame) so passing it a vector of the same length names your list

**Comment by thejmazz** [comment]
I didn't know about `names` to be assignable, so thats cool, thanks. But I still don't see how these twe objects (`fantom` and `named_list`) are of the same type, yet the latter is printed differently. Perhaps it is just that it is way longer and outputted differently (except `named_list <- list(1:10000, sample(LETTERS, 10000, replace=TRUE))` behaves like `named_list` and not like `fantom`).

``` r
> named_list <- list(c(1,2,3), c("a","b","c"))
> named_list
[[1]]
[1] 1 2 3

[[2]]
[1] "a" "b" "c"

> names(named_list)
NULL
> names(named_list) <- c("nums", "letters")
> named_list
$nums
[1] 1 2 3

$letters
[1] "a" "b" "c"

> typeof(named_list)
[1] "list"
> typeof(fantom@.kv)
[1] "list"
> head(fantom@.kv)
     stanza_id            key                value
1    .__Root__ format-version                  1.2
6    .__Root__       ontology ff/subsets/ff-phase2
10 BFO:0000030           name               object
11 BFO:0000030      namespace               FANTOM
12 BFO:0000030           is_a          BFO:0000040
16 BFO:0000040           name      material entity
# different from named_list in that its not
# $stanza_id
# [1] ".__Root__" ".__Root__" "BFO:0000030"
```

**Comment by thejmazz** [comment]
Sooo, a `data.frame` is a list. (?) My confusion between named lists and data frames was unnecessary. 

``` r
> a <- data.frame(nums=c(1,2,3), letters=c("a", "b", "c"))
> a
  nums letters
1    1       a
2    2       b
3    3       c
> typeof(a)
[1] "list"
```

Also it says data frame in the docs..
